// Code generated by mockery v2.38.0. DO NOT EDIT.

package interactor

import mock "github.com/stretchr/testify/mock"

// Private is an autogenerated mock type for the Private type
type Private struct {
	mock.Mock
}

// NewPrivate creates a new instance of Private. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrivate(t interface {
	mock.TestingT
	Cleanup(func())
}) *Private {
	mock := &Private{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
