// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package public

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List All events
	// (GET /events)
	GetEvents(ctx echo.Context) error
	// Create a Events
	// (POST /events)
	CreateEvent(ctx echo.Context) error
	// Delete a Events
	// (DELETE /events/{eventsId})
	DeleteEvent(ctx echo.Context, eventsId string) error
	// Get a Events
	// (GET /events/{eventsId})
	GetEventByID(ctx echo.Context, eventsId string) error
	// Update a Events
	// (PUT /events/{eventsId})
	UpdateEvent(ctx echo.Context, eventsId string) error
	// Retrieve all ToDo items
	// (GET /todos)
	GetAllTodos(ctx echo.Context) error
	// Create a new ToDo item
	// (POST /todos)
	CreateTodo(ctx echo.Context) error
	// Remove item by ID
	// (DELETE /todos/{todoId})
	DeleteTodo(ctx echo.Context, todoId openapi_types.UUID) error
	// Get item by ID
	// (GET /todos/{todoId})
	GetTodo(ctx echo.Context, todoId openapi_types.UUID) error
	// Patch an existing ToDo item
	// (PATCH /todos/{todoId})
	PatchTodo(ctx echo.Context, todoId openapi_types.UUID) error
	// Substitute an existing ToDo item
	// (PUT /todos/{todoId})
	UpdateTodo(ctx echo.Context, todoId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetEvents(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEvents(ctx)
	return err
}

// CreateEvent converts echo context to params.
func (w *ServerInterfaceWrapper) CreateEvent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateEvent(ctx)
	return err
}

// DeleteEvent converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteEvent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "eventsId" -------------
	var eventsId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "eventsId", runtime.ParamLocationPath, ctx.Param("eventsId"), &eventsId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter eventsId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteEvent(ctx, eventsId)
	return err
}

// GetEventByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "eventsId" -------------
	var eventsId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "eventsId", runtime.ParamLocationPath, ctx.Param("eventsId"), &eventsId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter eventsId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventByID(ctx, eventsId)
	return err
}

// UpdateEvent converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateEvent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "eventsId" -------------
	var eventsId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "eventsId", runtime.ParamLocationPath, ctx.Param("eventsId"), &eventsId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter eventsId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateEvent(ctx, eventsId)
	return err
}

// GetAllTodos converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllTodos(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllTodos(ctx)
	return err
}

// CreateTodo converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTodo(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTodo(ctx)
	return err
}

// DeleteTodo converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTodo(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "todoId" -------------
	var todoId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "todoId", runtime.ParamLocationPath, ctx.Param("todoId"), &todoId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter todoId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTodo(ctx, todoId)
	return err
}

// GetTodo converts echo context to params.
func (w *ServerInterfaceWrapper) GetTodo(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "todoId" -------------
	var todoId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "todoId", runtime.ParamLocationPath, ctx.Param("todoId"), &todoId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter todoId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTodo(ctx, todoId)
	return err
}

// PatchTodo converts echo context to params.
func (w *ServerInterfaceWrapper) PatchTodo(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "todoId" -------------
	var todoId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "todoId", runtime.ParamLocationPath, ctx.Param("todoId"), &todoId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter todoId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchTodo(ctx, todoId)
	return err
}

// UpdateTodo converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTodo(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "todoId" -------------
	var todoId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "todoId", runtime.ParamLocationPath, ctx.Param("todoId"), &todoId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter todoId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTodo(ctx, todoId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/events", wrapper.GetEvents)
	router.POST(baseURL+"/events", wrapper.CreateEvent)
	router.DELETE(baseURL+"/events/:eventsId", wrapper.DeleteEvent)
	router.GET(baseURL+"/events/:eventsId", wrapper.GetEventByID)
	router.PUT(baseURL+"/events/:eventsId", wrapper.UpdateEvent)
	router.GET(baseURL+"/todos", wrapper.GetAllTodos)
	router.POST(baseURL+"/todos", wrapper.CreateTodo)
	router.DELETE(baseURL+"/todos/:todoId", wrapper.DeleteTodo)
	router.GET(baseURL+"/todos/:todoId", wrapper.GetTodo)
	router.PATCH(baseURL+"/todos/:todoId", wrapper.PatchTodo)
	router.PUT(baseURL+"/todos/:todoId", wrapper.UpdateTodo)

}
