// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package public

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Events Represent event resources
type Events struct {
	AllDay   *bool      `json:"all_day,omitempty"`
	End      *time.Time `json:"end,omitempty"`
	EventId  *string    `json:"event_id,omitempty"`
	Location *string    `json:"location,omitempty"`
	Start    *time.Time `json:"start,omitempty"`
	Title    *string    `json:"title,omitempty"`
}

// ToDo defines model for ToDo.
type ToDo struct {
	Description string              `json:"description"`
	DueDate     *time.Time          `json:"due_date,omitempty"`
	Title       string              `json:"title"`
	TodoId      *openapi_types.UUID `json:"todo_id,omitempty"`
}

// ToDoInput defines model for ToDoInput.
type ToDoInput struct {
	Description *string             `json:"description,omitempty"`
	DueDate     *openapi_types.Date `json:"due_date,omitempty"`
	Title       string              `json:"title"`
}

// ToDoInputPatch defines model for ToDoInputPatch.
type ToDoInputPatch struct {
	Description *string             `json:"description,omitempty"`
	DueDate     *openapi_types.Date `json:"due_date,omitempty"`
	Title       *string             `json:"title,omitempty"`
}

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = Events

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody = Events

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = ToDoInput

// PatchTodoJSONRequestBody defines body for PatchTodo for application/json ContentType.
type PatchTodoJSONRequestBody = ToDoInputPatch

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = ToDoInput
