// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package public

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ToDo defines model for ToDo.
type ToDo struct {
	Description string              `json:"description"`
	DueDate     *time.Time          `json:"due_date,omitempty"`
	Title       string              `json:"title"`
	TodoId      *openapi_types.UUID `json:"todo_id,omitempty"`
}

// ToDoInput defines model for ToDoInput.
type ToDoInput struct {
	Description *string             `json:"description,omitempty"`
	DueDate     *openapi_types.Date `json:"due_date,omitempty"`
	Title       string              `json:"title"`
}

// ToDoInputPatch defines model for ToDoInputPatch.
type ToDoInputPatch struct {
	Description *string             `json:"description,omitempty"`
	DueDate     *openapi_types.Date `json:"due_date,omitempty"`
	Title       *string             `json:"title,omitempty"`
}

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = ToDoInput

// PatchTodoJSONRequestBody defines body for PatchTodo for application/json ContentType.
type PatchTodoJSONRequestBody = ToDoInputPatch

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = ToDoInput
